In the FutureRepyExceptionHierarchy, there are many functions and methods that support (optionally) the ability to terminate themselves when continuing would mean exceeding some specified maximum run-time. In these cases, TimeoutException is raised.